In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dfs = pd.read_html('https://rate.bot.com.tw/xrt?Lang=zh-TW')
currency = dfs[0]
df = currency.iloc[:, 0:5]
df.columns = ["幣別", "現金匯率-本行買入", "現金匯率-本行賣出", "即期匯率-本行買入", "即期匯率-本行賣出"]
df['幣別'] = df['幣別'].str.extract(r'([A-Z]+)')
df

     幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出
0   USD    30.205    30.875    30.555    30.655
1   HKD     3.745     3.949     3.871     3.931
2   GBP      38.2     40.32      39.2     39.62
3   AUD     20.54     21.32     20.81     21.04
4   CAD     22.81     23.72      23.2     23.42
5   SGD     21.84     22.75     22.33     22.51
6   CHF     30.17     31.37     30.83     31.12
7   JPY    0.2724    0.2852    0.2797    0.2837
8   ZAR         -         -      2.02       2.1
9   SEK      2.77      3.29      3.11      3.21
10  NZD     19.03     19.88     19.41     19.61
11  THB    0.8873    1.0753    0.9959    1.0359
12  PHP    0.5232    0.6562         -         -
13  IDR   0.00183   0.00253         -         -
14  EUR     33.23     34.57     33.85     34.25
15  KRW   0.02418   0.02808         -         -
16  VND   0.00095   0.00145         -         -
17  MYR       6.2     7.844         -         -
18  CNY     4.225     4.387     4.297     4.347