In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot
import pandas as pd

In [13]:
dfs = pd.read_html('https://rate.bot.com.tw/xrt?Lang=zh-TW')

In [14]:
type(dfs)

list

In [41]:
currency = dfs[0]
currency

                        幣別                        現金匯率          \
                        幣別 Unnamed: 1_level_1     本行買入    本行賣出
0       美金 (USD)  美金 (USD)             30.205   30.875  30.555
1       港幣 (HKD)  港幣 (HKD)              3.745    3.949   3.871
2       英鎊 (GBP)  英鎊 (GBP)               38.2    40.32    39.2
3       澳幣 (AUD)  澳幣 (AUD)              20.54    21.32   20.81
4   加拿大幣 (CAD)  加拿大幣 (CAD)              22.81    23.72    23.2
5   新加坡幣 (SGD)  新加坡幣 (SGD)              21.84    22.75   22.33
6   瑞士法郎 (CHF)  瑞士法郎 (CHF)              30.17    31.37   30.83
7       日圓 (JPY)  日圓 (JPY)             0.2724   0.2852  0.2797
8     南非幣 (ZAR)  南非幣 (ZAR)                  -        -    2.02
9     瑞典幣 (SEK)  瑞典幣 (SEK)               2.77     3.29    3.11
10      紐元 (NZD)  紐元 (NZD)              19.03    19.88   19.41
11      泰幣 (THB)  泰幣 (THB)             0.8873   1.0753  0.9959
12  菲國比索 (PHP)  菲國比索 (PHP)             0.5232   0.6562       -
13    印尼幣 (IDR)  印尼幣 (IDR)            0.00183  0.00253       -
14      歐元 (EUR)  歐元 (EUR)              33.23    34.57   33.85
15      韓元 (KRW)  韓元 (KRW)            0.02418  0.02808       -
16    越南盾 (VND)  越南盾 (VND)            0.00095  0.00145       -
17    馬來幣 (MYR)  馬來幣 (MYR)                6.2    7.844       -
18    人民幣 (CNY)  人民幣 (CNY)              4.225    4.387   4.297

   Unnamed: 4_level_0 即期匯率                    Unnamed: 7_level_0     遠期匯率  \
                 本行買入 本行賣出 Unnamed: 6_level_1               本行買入     遠期匯率
0              30.655   查詢                 查詢             30.205   30.875
1               3.931   查詢                 查詢              3.745    3.949
2               39.62   查詢                 查詢               38.2    40.32
3               21.04   查詢                 查詢              20.54    21.32
4               23.42   查詢                 查詢              22.81    23.72
5               22.51   查詢                 查詢              21.84    22.75
6               31.12   查詢                 查詢              30.17    31.37
7              0.2837   查詢                 查詢             0.2724   0.2852
8                 2.1   查詢                 查詢                  -        -
9                3.21   查詢                 查詢               2.77     3.29
10              19.61   查詢                 查詢              19.03    19.88
11             1.0359   查詢                 查詢             0.8873   1.0753
12                  -   查詢                 查詢             0.5232   0.6562
13                  -   查詢                 查詢            0.00183  0.00253
14              34.25   查詢                 查詢              33.23    34.57
15                  -   查詢                 查詢            0.02418  0.02808
16                  -   查詢                 查詢            0.00095  0.00145
17                  -   查詢                 查詢                6.2    7.844
18              4.347   查詢                 查詢              4.225    4.387

      歷史匯率           現金匯率        Unnamed: 13_level_0                即期匯率  \
      歷史匯率    本行賣出 本行買入.1 本行賣出.1 Unnamed: 13_level_1 Unnamed: 14_level_1
0   30.555  30.655    NaN    NaN                 NaN                 NaN
1    3.871   3.931    NaN    NaN                 NaN                 NaN
2     39.2   39.62    NaN    NaN                 NaN                 NaN
3    20.81   21.04    NaN    NaN                 NaN                 NaN
4     23.2   23.42    NaN    NaN                 NaN                 NaN
5    22.33   22.51    NaN    NaN                 NaN                 NaN
6    30.83   31.12    NaN    NaN                 NaN                 NaN
7   0.2797  0.2837    NaN    NaN                 NaN                 NaN
8     2.02     2.1    NaN    NaN                 NaN                 NaN
9     3.11    3.21    NaN    NaN                 NaN                 NaN
10   19.41   19.61    NaN    NaN                 NaN                 NaN
11  0.9959  1.0359    NaN    NaN                 NaN                 NaN
12       -       -    NaN    NaN                 NaN                 NaN
13       -       -    NaN    NaN                 NaN                 NaN
14   33.85   34.25    NaN    NaN                 NaN                 NaN
15       -       -    NaN    NaN                 NaN                 NaN
16       -       -    NaN    NaN                 NaN                 NaN
17       -       -    NaN    NaN                 NaN                 NaN
18   4.297   4.347    NaN    NaN                 NaN                 NaN

                       Unnamed: 16_level_0
   Unnamed: 15_level_1 Unnamed: 16_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN

In [42]:
type(currency)

pandas.core.frame.DataFrame

In [52]:
df = currency.iloc[:, 0:5]

In [53]:
df

                        幣別                        現金匯率          \
                        幣別 Unnamed: 1_level_1     本行買入    本行賣出
0       美金 (USD)  美金 (USD)             30.205   30.875  30.555
1       港幣 (HKD)  港幣 (HKD)              3.745    3.949   3.871
2       英鎊 (GBP)  英鎊 (GBP)               38.2    40.32    39.2
3       澳幣 (AUD)  澳幣 (AUD)              20.54    21.32   20.81
4   加拿大幣 (CAD)  加拿大幣 (CAD)              22.81    23.72    23.2
5   新加坡幣 (SGD)  新加坡幣 (SGD)              21.84    22.75   22.33
6   瑞士法郎 (CHF)  瑞士法郎 (CHF)              30.17    31.37   30.83
7       日圓 (JPY)  日圓 (JPY)             0.2724   0.2852  0.2797
8     南非幣 (ZAR)  南非幣 (ZAR)                  -        -    2.02
9     瑞典幣 (SEK)  瑞典幣 (SEK)               2.77     3.29    3.11
10      紐元 (NZD)  紐元 (NZD)              19.03    19.88   19.41
11      泰幣 (THB)  泰幣 (THB)             0.8873   1.0753  0.9959
12  菲國比索 (PHP)  菲國比索 (PHP)             0.5232   0.6562       -
13    印尼幣 (IDR)  印尼幣 (IDR)            0.00183  0.00253       -
14      歐元 (EUR)  歐元 (EUR)              33.23    34.57   33.85
15      韓元 (KRW)  韓元 (KRW)            0.02418  0.02808       -
16    越南盾 (VND)  越南盾 (VND)            0.00095  0.00145       -
17    馬來幣 (MYR)  馬來幣 (MYR)                6.2    7.844       -
18    人民幣 (CNY)  人民幣 (CNY)              4.225    4.387   4.297

   Unnamed: 4_level_0
                 本行買入
0              30.655
1               3.931
2               39.62
3               21.04
4               23.42
5               22.51
6               31.12
7              0.2837
8                 2.1
9                3.21
10              19.61
11             1.0359
12                  -
13                  -
14              34.25
15                  -
16                  -
17                  -
18              4.347

In [54]:
df.columns=["幣別","現金匯率-本行買入","現金匯率-本行賣出","即期匯率-本行買入","即期匯率-本行賣出"]

In [55]:
df

                        幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出
0       美金 (USD)  美金 (USD)    30.205    30.875    30.555    30.655
1       港幣 (HKD)  港幣 (HKD)     3.745     3.949     3.871     3.931
2       英鎊 (GBP)  英鎊 (GBP)      38.2     40.32      39.2     39.62
3       澳幣 (AUD)  澳幣 (AUD)     20.54     21.32     20.81     21.04
4   加拿大幣 (CAD)  加拿大幣 (CAD)     22.81     23.72      23.2     23.42
5   新加坡幣 (SGD)  新加坡幣 (SGD)     21.84     22.75     22.33     22.51
6   瑞士法郎 (CHF)  瑞士法郎 (CHF)     30.17     31.37     30.83     31.12
7       日圓 (JPY)  日圓 (JPY)    0.2724    0.2852    0.2797    0.2837
8     南非幣 (ZAR)  南非幣 (ZAR)         -         -      2.02       2.1
9     瑞典幣 (SEK)  瑞典幣 (SEK)      2.77      3.29      3.11      3.21
10      紐元 (NZD)  紐元 (NZD)     19.03     19.88     19.41     19.61
11      泰幣 (THB)  泰幣 (THB)    0.8873    1.0753    0.9959    1.0359
12  菲國比索 (PHP)  菲國比索 (PHP)    0.5232    0.6562         -         -
13    印尼幣 (IDR)  印尼幣 (IDR)   0.00183   0.00253         -         -
14      歐元 (EUR)  歐元 (EUR)     33.23     34.57     33.85     34.25
15      韓元 (KRW)  韓元 (KRW)   0.02418   0.02808         -         -
16    越南盾 (VND)  越南盾 (VND)   0.00095   0.00145         -         -
17    馬來幣 (MYR)  馬來幣 (MYR)       6.2     7.844         -         -
18    人民幣 (CNY)  人民幣 (CNY)     4.225     4.387     4.297     4.347

In [60]:
df['幣別'].str.extract(r'([A-Z]+)')

#正規運算式 (regular expression) 常用在對文件進行解析，例如做網路爬蟲去爬網路上的 HTML 文件，從中取得所欲取得之資訊，或是針對文件檔案進行處理。
#Python 中做正規運算式的模組為 re ，首先要設定好配對形式 (pattern) 字串 (string) ，然後以該配對形式字串與所欲處理之字串利用 re 中相關功能的函數 (function) 進行處理。
#配對形式字串通常會用以 r 開始的原始字串 (raw string) ，例如 r"str" 
#https://kaiching.org/pydoing/py/python-library-re.html。

      0
0   USD
1   HKD
2   GBP
3   AUD
4   CAD
5   SGD
6   CHF
7   JPY
8   ZAR
9   SEK
10  NZD
11  THB
12  PHP
13  IDR
14  EUR
15  KRW
16  VND
17  MYR
18  CNY

In [62]:
df['幣別'] = df['幣別'].str.extract(r'([A-Z]+)') #如果沒有打 [A-Z]+ 的+的話 只會跑出第一個英文字

In [63]:
df

     幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出
0   USD    30.205    30.875    30.555    30.655
1   HKD     3.745     3.949     3.871     3.931
2   GBP      38.2     40.32      39.2     39.62
3   AUD     20.54     21.32     20.81     21.04
4   CAD     22.81     23.72      23.2     23.42
5   SGD     21.84     22.75     22.33     22.51
6   CHF     30.17     31.37     30.83     31.12
7   JPY    0.2724    0.2852    0.2797    0.2837
8   ZAR         -         -      2.02       2.1
9   SEK      2.77      3.29      3.11      3.21
10  NZD     19.03     19.88     19.41     19.61
11  THB    0.8873    1.0753    0.9959    1.0359
12  PHP    0.5232    0.6562         -         -
13  IDR   0.00183   0.00253         -         -
14  EUR     33.23     34.57     33.85     34.25
15  KRW   0.02418   0.02808         -         -
16  VND   0.00095   0.00145         -         -
17  MYR       6.2     7.844         -         -
18  CNY     4.225     4.387     4.297     4.347

In [65]:
c = df['現金匯率-本行賣出']
c

0      30.875
1       3.949
2       40.32
3       21.32
4       23.72
5       22.75
6       31.37
7      0.2852
8           -
9        3.29
10      19.88
11     1.0753
12     0.6562
13    0.00253
14      34.57
15    0.02808
16    0.00145
17      7.844
18      4.387
Name: 現金匯率-本行賣出, dtype: object

In [66]:
type(c)

pandas.core.series.Series

In [71]:
money = df['幣別']
money

0     USD
1     HKD
2     GBP
3     AUD
4     CAD
5     SGD
6     CHF
7     JPY
8     ZAR
9     SEK
10    NZD
11    THB
12    PHP
13    IDR
14    EUR
15    KRW
16    VND
17    MYR
18    CNY
Name: 幣別, dtype: object

In [77]:
df3 = pd.concat([money,c], axis=1 )
df3.columns=["幣別","匯率"]
df3

     幣別       匯率
0   USD   30.875
1   HKD    3.949
2   GBP    40.32
3   AUD    21.32
4   CAD    23.72
5   SGD    22.75
6   CHF    31.37
7   JPY   0.2852
8   ZAR        -
9   SEK     3.29
10  NZD    19.88
11  THB   1.0753
12  PHP   0.6562
13  IDR  0.00253
14  EUR    34.57
15  KRW  0.02808
16  VND  0.00145
17  MYR    7.844
18  CNY    4.387

In [81]:
df3['換算台幣']=df['匯率'].map(lambda x: x**2)

pandas.core.frame.DataFrame

In [89]:
c1 = list(c)
c1

['30.875',
 '3.949',
 '40.32',
 '21.32',
 '23.72',
 '22.75',
 '31.37',
 '0.2852',
 '-',
 '3.29',
 '19.88',
 '1.0753',
 '0.6562',
 '0.00253',
 '34.57',
 '0.02808',
 '0.00145',
 '7.844',
 '4.387']

In [90]:
price = input("請輸入你想購買的商品價格")
for p in price:
    p = int(p)
    print(p*c1)

請輸入你想購買的商品價格100
['30.875', '3.949', '40.32', '21.32', '23.72', '22.75', '31.37', '0.2852', '-', '3.29', '19.88', '1.0753', '0.6562', '0.00253', '34.57', '0.02808', '0.00145', '7.844', '4.387']
[]
[]

In [ ]:
def exchange(p):
    p = float(p)
    return p*c1